.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wb300 1  "wb300 2.0.0"
.SH NAME
wb300 \- Live TUI control tower for the branches and worktrees used by parallel coding agents
.SH SYNOPSIS
\fBwb300\fR [\fB\-\-repo\fR] [\fB\-\-no\-live\fR] [\fB\-\-home\fR] [\fB\-\-no\-alt\-screen\fR] [\fB\-\-no\-color\fR] [\fB\-\-no\-notify\fR] [\fB\-\-print\-selected\-path\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Live TUI control tower for the branches and worktrees used by parallel coding agents
.SH OPTIONS
.TP
\fB\-\-repo\fR \fI<PATH>\fR

.TP
\fB\-\-no\-live\fR

.TP
\fB\-\-home\fR

.TP
\fB\-\-no\-alt\-screen\fR

.TP
\fB\-\-no\-color\fR

.TP
\fB\-\-no\-notify\fR

.TP
\fB\-\-print\-selected\-path\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
wb300\-help(1)
.TP
wb300\-update(1)
.TP
wb300\-agent(1)
.TP
wb300\-uninstall(1)
.SH VERSION
v2.0.0
